const Airtable = require('airtable');
const { tierIncludes, normalizeTier } = require('./lib/tiers');

// Scheduled (weekly) — see netlify.toml [functions."generate-social"] schedule.
// For each Concierge client (tier includes 'social_posts'), emit a small batch of
// ready-to-post social captions across platforms. If OPENAI_API_KEY is present the
// captions are generated by the model from the business context; otherwise a
// deterministic template set is used (records-only style, like the rest of GS).
//
// Idempotent within a run: a client won't get a second copy of a caption whose
// Caption text is already sitting in 'new' status for them.
//
// Also manually invokable (GET/POST) for testing; returns a JSON summary.

const PLATFORMS = ['instagram', 'facebook', 'twitter', 'linkedin'];

// Deterministic fallback captions when no OpenAI key is present. One per category.
function templatePosts(company) {
    const name = company || 'our shop';
    return [
        {
            platform: 'instagram',
            category: 'promo',
            caption: `Treat yourself today at ${name}! Swing by or order online — we saved a spot just for you.`,
            hashtags: '#shoplocal #smallbusiness #supportlocal'
        },
        {
            platform: 'facebook',
            category: 'engagement',
            caption: `What's your go-to order at ${name}? Drop it in the comments — we love hearing your favorites!`,
            hashtags: '#community #localfavorites'
        },
        {
            platform: 'instagram',
            category: 'seasonal',
            caption: `The season's here and so are fresh picks at ${name}. Come see what's new this week.`,
            hashtags: '#seasonal #newarrivals #shoplocal'
        },
        {
            platform: 'twitter',
            category: 'announcement',
            caption: `Big things happening at ${name} this week. Follow along so you don't miss out.`,
            hashtags: '#smallbusiness #local'
        }
    ];
}

// Optional OpenAI generation — produces platform-ready captions from the business.
async function generatePosts(company, category) {
    if (!process.env.OPENAI_API_KEY) return templatePosts(company);
    try {
        const { OpenAI } = require('openai');
        const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
        const completion = await openai.chat.completions.create({
            model: 'gpt-3.5-turbo',
            messages: [
                { role: 'system', content: 'You are a social media manager for small local businesses. Produce 4 ready-to-post captions, one each for instagram, facebook, twitter, and linkedin. Each under 40 words, warm and specific, no markdown. Return ONLY a JSON array of objects: {"platform","category","caption","hashtags"}. Category is one of promo, engagement, seasonal, announcement. Hashtags is a single space-separated string.' },
                { role: 'user', content: `Business: ${company || 'a small local business'}` }
            ],
            temperature: 0.8,
            max_tokens: 600
        });
        let raw = completion.choices[0].message.content || '';
        raw = raw.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, '').trim();
        const posts = JSON.parse(raw);
        if (Array.isArray(posts) && posts.length) {
            return posts
                .filter(p => p && p.caption)
                .map(p => ({
                    platform: PLATFORMS.includes((p.platform || '').toLowerCase()) ? p.platform.toLowerCase() : 'instagram',
                    category: ['promo', 'engagement', 'seasonal', 'announcement'].includes((p.category || '').toLowerCase()) ? p.category.toLowerCase() : 'promo',
                    caption: String(p.caption).trim(),
                    hashtags: typeof p.hashtags === 'string' ? p.hashtags.trim() : ''
                }));
        }
    } catch (e) {
        // Fall back to template copy on any parse/API error.
    }
    return templatePosts(company);
}

async function runGenerate() {
    const apiKey = process.env.AIRTABLE_API_KEY;
    const base = new Airtable({ apiKey }).base(process.env.AIRTABLE_BASE_ID);

    const clients = await base('Clients').select({ maxRecords: 500 }).all();

    let generated = 0;
    let skipped = 0;
    const rows = [];

    for (const client of clients) {
        const tier = normalizeTier(client.get('Tier'));
        if (!tierIncludes(tier, 'social_posts')) { skipped++; continue; }

        const company = client.get('Company') || client.get('Name') || '';

        // Existing open posts for this client (dedupe by Caption).
        let openCaptions = new Set();
        try {
            const existing = await base('SocialPosts').select({
                filterByFormula: `AND({ClientID} = '${client.id}', {Status} = 'new')`,
                maxRecords: 100
            }).all();
            openCaptions = new Set(existing.map(r => r.get('Caption')));
        } catch (e) {
            return { error: 'SocialPosts table not found', generated: 0 };
        }

        let posts = await generatePosts(company);
        posts = posts.filter(p => !openCaptions.has(p.caption));
        if (!posts.length) { skipped++; continue; }

        const nowIso = new Date().toISOString();
        for (const p of posts) {
            rows.push({
                fields: {
                    PostID: 'post_' + Date.now() + '_' + Math.random().toString(36).slice(2, 8),
                    ClientID: client.id,
                    Platform: p.platform,
                    Caption: p.caption,
                    Hashtags: p.hashtags || '',
                    Category: p.category,
                    Status: 'new',
                    ScheduledFor: '',
                    CreatedAt: nowIso
                }
            });
            generated++;
        }
    }

    // Write in chunks of 10 (Airtable cap), throttled.
    for (let i = 0; i < rows.length; i += 10) {
        await base('SocialPosts').create(rows.slice(i, i + 10));
        await new Promise(r => setTimeout(r, 250));
    }

    return { generated, skipped, total: clients.length };
}

exports.handler = async () => {
    try {
        const result = await runGenerate();
        console.log('Social generation complete:', JSON.stringify(result));
        return { statusCode: 200, body: JSON.stringify({ success: true, ...result }) };
    } catch (error) {
        console.error('Generate social error:', error);
        return { statusCode: 500, body: JSON.stringify({ error: 'Social generation failed' }) };
    }
};
