const PDFDocument = require('pdfkit');

// Builds a one-page monthly performance report PDF and resolves with a Buffer.
// Kept dependency-light (no external fonts/images) so it bundles cleanly into a
// Netlify function. Used by both generate-reports (validation) and get-reports
// (on-demand download).
//
// stats: { views, orders, revenue, avgOrder, viewsSeries?: [{date,count}],
//          revenueSeries?: [{date,revenue,orders}], ordersByStatus?: {} }
function buildReportPDF({ company, period, stats }) {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ size: 'LETTER', margin: 50 });
            const chunks = [];
            doc.on('data', (c) => chunks.push(c));
            doc.on('end', () => resolve(Buffer.concat(chunks)));
            doc.on('error', reject);

            const gold = '#d4af37';
            const dark = '#1a1a2e';
            const muted = '#8892a0';

            // Header band
            doc.rect(0, 0, doc.page.width, 90).fill(dark);
            doc.fillColor(gold).fontSize(22).text('Global Storefront', 50, 30);
            doc.fillColor('#ffffff').fontSize(11).text('Monthly Performance Report', 50, 58);

            // Title block
            doc.moveDown(3);
            doc.fillColor(dark).fontSize(18).text(company || 'Your Business', 50, 120);
            doc.fillColor(muted).fontSize(12).text('Reporting period: ' + (period || ''), 50, 146);

            // Divider
            doc.moveTo(50, 175).lineTo(doc.page.width - 50, 175).strokeColor('#e8e5e0').stroke();

            // Stat rows
            const rows = [
                ['Total Page Views', String(stats.views ?? 0)],
                ['Total Orders', String(stats.orders ?? 0)],
                ['Total Revenue', '$' + Number(stats.revenue ?? 0).toLocaleString()],
                ['Average Order Value', stats.orders > 0 ? '$' + Number(stats.avgOrder ?? 0).toLocaleString() : '—']
            ];
            let y = 200;
            rows.forEach(([label, value]) => {
                doc.fillColor(muted).fontSize(12).text(label, 50, y);
                doc.fillColor(dark).fontSize(14).text(value, 300, y, { align: 'right', width: doc.page.width - 350 });
                y += 34;
            });

            // Orders by status
            const statusObj = stats.ordersByStatus || {};
            const statusKeys = Object.keys(statusObj);
            if (statusKeys.length) {
                y += 10;
                doc.fillColor(dark).fontSize(14).text('Orders by Status', 50, y);
                y += 26;
                statusKeys.forEach((k) => {
                    doc.fillColor(muted).fontSize(11).text(k, 60, y);
                    doc.fillColor(dark).fontSize(11).text(String(statusObj[k]), 300, y, { align: 'right', width: doc.page.width - 350 });
                    y += 20;
                });
            }

            // Footer
            doc.fillColor(muted).fontSize(9).text(
                'Generated by Global Storefront on ' + new Date().toISOString().split('T')[0],
                50, doc.page.height - 60, { align: 'center', width: doc.page.width - 100 }
            );

            doc.end();
        } catch (err) {
            reject(err);
        }
    });
}

module.exports = { buildReportPDF };
